[package]
name = "language-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
cocoa = "0.24"
objc = "0.2"
serde_json = "1.0.140"

[target.'cfg(target_os = "macos")'.build-dependencies]
cc = "1.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true 